url_param:
  sise_quant_high:
    kospi: "https://finance.naver.com/sise/sise_quant_high.nhn?sosok=0"
    kosdak: "https://finance.naver.com/sise/sise_quant_high.nhn?sosok=1"
  sise_low_up:
    kospi: "https://finance.naver.com/sise/sise_low_up.nhn?sosok=0"
    kosdak: "https://finance.naver.com/sise/sise_low_up.nhn?sosok=1"
  sise_rising:
    kospi: "https://finance.naver.com/sise/sise_rise.nhn?sosok=0"
    kosdak: "https://finance.naver.com/sise/sise_rise.nhn?sosok=1"
  quick_news: "https://finance.naver.com/news/news_list.nhn?mode=RANK"

query_param:
  from_up_vol_rt: 10.0
  to_up_vol_rt: 5000.0
  from_price: 5000
  to_price: 25000
  roe: 0.0
  from_up_prc_rt: 1.2
  to_up_prc_rt: 3.0
  low_vs_rt: 3.0
  gap_low_vs_rt: 1.5
  gap_prc_rt: 1.0
  gap_vol_rt: 10.0
  vol: 500000

hms_param:
  start_hms: "090030"
  end_hms: "093000"
  until_hms: "100000"
  clear_hms: "103000"

base_amount: 1000000
jongmok_cnt: 3